name: Main workflow

on:
  - workflow_dispatch
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            name: 1
          - os: macos-latest
            name: 2
          - os: macos-latest
            name: 3
          - os: macos-latest
            name: 4
          - os: macos-latest
            name: 5

    runs-on: ${{ matrix.os }}
    
    env:
      HOMEBREW_NO_ANALYTICS: "1"

    steps:
      - run: brew update
      - run: brew fetch sysbench libevent luajit-openresty mysql-client openssl@1.1 zstd
      - run: brew install sysbench

      - run: sysbench cpu run
      - run: sysbench memory run
      - run: sysbench fileio prepare
      - run: sysbench fileio --file-test-mode=seqrd run
      - run: sysbench fileio prepare
      - run: sysbench fileio --file-test-mode=seqwr run
      - run: sysbench fileio prepare
      - run: sysbench fileio --file-test-mode=rndrw run
